version: "3"
 
services:
  miservicio_mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=Ejemplo
      - MYSQL_ROOT_PASSWORD=esponda2
      - MYSQL_USER=Cristell
      - MYSQL_PASSWORD=esponda2
    volumes:
      # Montamos un volumen para MySQL para no perder los datos de bd
      - ./volumenes/mysql:/var/lib/mysql
    expose:
      - 3307
    ports:
      - 3307:3307
   
  miserviciocristell:
    image: webdevops/php-apache
    volumes:
      # Montamos nuestra web desde fuera en el directorio web del contenedor
      - ./miweb/:/app
    expose:
      - 80
    ports:
      - 80:80
    links: 
      - miservicio_mysql